apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-b3mt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-b3mt
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-b3mt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-b3mt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-b3mt
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kpjp-tenant/rhtap-demo-app/hacbs-test-project-b3mt@sha256:73ca46d3e327fc3ac8a3ad17c3c61c530a15266fac97766b0db09593a9eccedb
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
